### ISSUE TITLE
Github actions regularly fail to download eol.php

### ISSUE THREAD

**Issue by lightswitch05** [lightswitch05/php-version-audit#32]
For some reason, the Github Actions script regularly fails to download `https://www.php.net/eol.php`. This is a problem as it breaks the entire self-updating of PHP Version Audit. Need to spend some time figuring this out, at least get the HTTP status code of the failure. Logs:

```
2020-05-06T11:43:37.0214417Z {
2020-05-06T11:43:37.0216985Z     "level": "info",
2020-05-06T11:43:37.0217951Z     "time": "2020-05-06T11:43:37+0000",
2020-05-06T11:43:37.0218157Z     "message": "Beginning EOL parse."
2020-05-06T11:43:37.0218346Z }
2020-05-06T11:46:28.3398079Z {
2020-05-06T11:46:28.3398386Z     "level": "debug",
2020-05-06T11:46:28.3402961Z     "time": "2020-05-06T11:46:28+0000",
2020-05-06T11:46:28.3403358Z     "message": "Downloading attempt 0: https://www.php.net/eol.php"
2020-05-06T11:46:28.3403678Z }
2020-05-06T11:47:14.8277473Z {
2020-05-06T11:47:14.8278315Z     "level": "debug",
2020-05-06T11:47:14.8280222Z     "time": "2020-05-06T11:47:14+0000",
2020-05-06T11:47:14.8280937Z     "message": "Downloading attempt 1: https://www.php.net/eol.php"
2020-05-06T11:47:14.8281634Z }
2020-05-06T11:48:01.4197584Z {
2020-05-06T11:48:01.4198312Z     "level": "debug",
2020-05-06T11:48:01.4199811Z     "time": "2020-05-06T11:48:01+0000",
2020-05-06T11:48:01.4200408Z     "message": "Downloading attempt 2: https://www.php.net/eol.php"
2020-05-06T11:48:01.4200836Z }
2020-05-06T11:48:48.0116825Z {
2020-05-06T11:48:48.0117877Z     "level": "debug",
2020-05-06T11:48:48.0119209Z     "time": "2020-05-06T11:48:48+0000",
2020-05-06T11:48:48.0119584Z     "message": "Downloading attempt 3: https://www.php.net/eol.php"
2020-05-06T11:48:48.0119931Z }
2020-05-06T11:49:19.6042830Z PHP Fatal error:  Uncaught lightswitch05\PhpVersionAudit\Exceptions\DownloadException: Download error: Unable to download: https://www.php.net/eol.php in /home/runner/work/php-version-audit/php-version-audit/src/Exceptions/DownloadException.php:15
2020-05-06T11:49:19.6043839Z Stack trace:
2020-05-06T11:49:19.6045679Z #0 /home/runner/work/php-version-audit/php-version-audit/src/CachedDownload.php(117): lightswitch05\PhpVersionAudit\Exceptions\DownloadException::fromString()
2020-05-06T11:49:19.6046944Z #1 /home/runner/work/php-version-audit/php-version-audit/src/CachedDownload.php(115): lightswitch05\PhpVersionAudit\CachedDownload::downloadFile()
2020-05-06T11:49:19.6047779Z #2 /home/runner/work/php-version-audit/php-version-audit/src/CachedDownload.php(115): lightswitch05\PhpVersionAudit\CachedDownload::downloadFile()
2020-05-06T11:49:19.6048566Z #3 /home/runner/work/php-version-audit/php-version-audit/src/CachedDownload.php(115): lightswitch05\PhpVersionAudit\CachedDownload::downloadFile()
2020-05-06T11:49:19.6049348Z #4 /home/runner/work/php-version-audit/php-version-audit/src/CachedDownload.php(74): lightswitch05\PhpVersionAudit\CachedDownload::downloadFile()
2020-05-06T11:49:19.6049894Z #5 /home/runner/work/php-version-au in /home/runner/work/php-version-audit/php-version-audit/src/Exceptions/DownloadException.php on line 15
2020-05-06T11:49:19.6157888Z ##[error]Process completed with exit code 255.
```

**Comment by lightswitch05** [comment]
Bug ticket: https://bugs.php.net/bug.php?id=79445

**Comment by lightswitch05** [comment]
seems like this has been resolved
